Sync with Upstream

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -38,20 +38,12 @@ jobs:
           echo "${DELIM}" >> "$GITHUB_OUTPUT"
 
           cd build
-          yt_op=$(find . -maxdepth 1 -name "youtube-revanced-extended-magisk-*.zip" -printf '%P')
-          echo "YT_OUTPUT=$yt_op" >> $GITHUB_OUTPUT
+          yt_op=$(find . -maxdepth 1 -name "youtube-revanced-magisk-*.zip" -printf '%P')
           if [ -z "$yt_op" ]; then
-            echo "RELEASE_NAME="ReVanced Extended APKs"" >> $GITHUB_OUTPUT
+            echo "RELEASE_NAME=ReVanced Extended APKs" >> $GITHUB_OUTPUT
           else
-            echo "RELEASE_NAME="ReVanced Extended Modules"" >> $GITHUB_OUTPUT
+            echo "RELEASE_NAME=ReVanced Extended Modules/APKs" >> $GITHUB_OUTPUT
           fi
-          echo "MUSIC_OUTPUT_ARM64=$(find . -maxdepth 1 -name "music-revanced-extended-magisk-*-arm64-v8a.zip" -printf '%P')" >> $GITHUB_OUTPUT
-          echo "MUSIC_OUTPUT_ARM=$(find . -maxdepth 1 -name "music-revanced-extended-magisk-*-arm-v7a.zip" -printf '%P')" >> $GITHUB_OUTPUT
-          echo "TW_OUTPUT=$(find . -maxdepth 1 -name "twitter-revanced-magisk-*.zip" -printf '%P')" >> $GITHUB_OUTPUT
-          echo "RDT_OUTPUT=$(find . -maxdepth 1 -name "reddit-revanced-magisk-*.zip" -printf '%P')" >> $GITHUB_OUTPUT
-          echo "TT_OUTPUT=$(find . -maxdepth 1 -name "tiktok-revanced-magisk-*.zip" -printf '%P')" >> $GITHUB_OUTPUT
-          echo "SP_OUTPUT=$(find . -maxdepth 1 -name "spotify-revanced-magisk-*.zip" -printf '%P')" >> $GITHUB_OUTPUT
-          echo "WW_OUTPUT=$(find . -maxdepth 1 -name "warnwetter-revanced-magisk-*.zip" -printf '%P')" >> $GITHUB_OUTPUT
 
       - name: Upload modules to release
         uses: svenstaro/upload-release-action@2.3.0
@@ -70,72 +62,29 @@ jobs:
       - name: Update changelog and Magisk update jsons
         id: update_config
         run: |
-          echo '${{ steps.get_output.outputs.BUILD_LOG }}' >build.md
-          CHANGELOG_URL="https://raw.githubusercontent.com/$GITHUB_REPOSITORY/update/build.md"
           get_update_json() {
             echo "{
-            \"version\": \"v$1\",
+            \"version\": \"$1\",
             \"versionCode\": $2,
             \"zipUrl\": \"$3\",
-            \"changelog\": \"$4\"
+            \"changelog\": \"https://raw.githubusercontent.com/$GITHUB_REPOSITORY/update/build.md\"
           }"
           }
-          if [ -n "${{ steps.get_output.outputs.YT_OUTPUT }}" ]; then
-            YT_VER=$(sed -n 's/.*YouTube: \(.*\)/\1/p' build.md | xargs)
-            YT_DLURL="$GITHUB_SERVER_URL/$GITHUB_REPOSITORY/releases/download/${{ steps.next_ver_code.outputs.NEXT_VER_CODE }}/${{ steps.get_output.outputs.YT_OUTPUT }}"
-            UPDATE_YT_JSON=$(get_update_json "$YT_VER" "${{ steps.next_ver_code.outputs.NEXT_VER_CODE}}" "$YT_DLURL" "$CHANGELOG_URL")
-            echo "$UPDATE_YT_JSON" >yt-update.json
-          fi
 
-          if [ -n "${{ steps.get_output.outputs.MUSIC_OUTPUT_ARM64 }}" ]; then
-            MUSIC_VER=$(sed -n 's/.*Music (arm64-v8a): \(.*\)/\1/p' build.md | xargs)
-            MUSIC_ARM64_DLURL="$GITHUB_SERVER_URL/$GITHUB_REPOSITORY/releases/download/${{ steps.next_ver_code.outputs.NEXT_VER_CODE }}/${{ steps.get_output.outputs.MUSIC_OUTPUT_ARM64 }}"
-            UPDATE_MUSIC_ARM64_JSON=$(get_update_json "$MUSIC_VER" "${{ steps.next_ver_code.outputs.NEXT_VER_CODE }}" "$MUSIC_ARM64_DLURL" "$CHANGELOG_URL")
-            echo "$UPDATE_MUSIC_ARM64_JSON" >music-update-arm64-v8a.json
-          fi
+          cd build || echo "build folder not found"
+          for OUTPUT in *revanced*.zip; do
+            [ "$OUTPUT" = "*revanced*.zip" ] && continue
+            ZIP_S=$(unzip -p "$OUTPUT" module.prop)
+            UPDATE_JSON=$(echo "$ZIP_S" | grep updateJson)
+            UPDATE_JSON="${UPDATE_JSON##*/}"
+            VER=$(echo "$ZIP_S" | grep version=)
+            VER="${VER##*=}"
+            DLURL="$GITHUB_SERVER_URL/$GITHUB_REPOSITORY/releases/download/${{ steps.next_ver_code.outputs.NEXT_VER_CODE }}/${OUTPUT}"
+            get_update_json "$VER" "${{ steps.next_ver_code.outputs.NEXT_VER_CODE}}" "$DLURL" "$CHANGELOG_URL" >"../$UPDATE_JSON"
+          done
+          cd ..
 
-          if [ -n "${{ steps.get_output.outputs.MUSIC_OUTPUT_ARM }}" ]; then
-            MUSIC_VER=$(sed -n 's/.*Music (arm-v7a): \(.*\)/\1/p' build.md | xargs)
-            MUSIC_ARM_DLURL="$GITHUB_SERVER_URL/$GITHUB_REPOSITORY/releases/download/${{ steps.next_ver_code.outputs.NEXT_VER_CODE }}/${{ steps.get_output.outputs.MUSIC_OUTPUT_ARM }}"
-            UPDATE_MUSIC_ARM_JSON=$(get_update_json "$MUSIC_VER" "${{ steps.next_ver_code.outputs.NEXT_VER_CODE }}" "$MUSIC_ARM_DLURL" "$CHANGELOG_URL")
-            echo "$UPDATE_MUSIC_ARM_JSON" >music-update-arm-v7a.json
-          fi
-
-          if [ -n "${{ steps.get_output.outputs.TW_OUTPUT }}" ]; then
-            TW_VER=$(sed -n 's/.*Twitter: \(.*\)/\1/p' build.md | xargs)
-            TW_DLURL="$GITHUB_SERVER_URL/$GITHUB_REPOSITORY/releases/download/${{ steps.next_ver_code.outputs.NEXT_VER_CODE }}/${{ steps.get_output.outputs.TW_OUTPUT }}"
-            UPDATE_TW_JSON=$(get_update_json "$TW_VER" "${{ steps.next_ver_code.outputs.NEXT_VER_CODE}}" "$TW_DLURL" "$CHANGELOG_URL")
-            echo "$UPDATE_TW_JSON" >tw-update.json
-          fi
-
-          if [ -n "${{ steps.get_output.outputs.RDT_OUTPUT }}" ]; then
-            RDT_VER=$(sed -n 's/.*Reddit: \(.*\)/\1/p' build.md | xargs)
-            RDT_DLURL="$GITHUB_SERVER_URL/$GITHUB_REPOSITORY/releases/download/${{ steps.next_ver_code.outputs.NEXT_VER_CODE }}/${{ steps.get_output.outputs.RDT_OUTPUT }}"
-            UPDATE_RDT_JSON=$(get_update_json "$RDT_VER" "${{ steps.next_ver_code.outputs.NEXT_VER_CODE}}" "$RDT_DLURL" "$CHANGELOG_URL")
-            echo "$UPDATE_RDT_JSON" >rdt-update.json
-          fi
-
-          if [ -n "${{ steps.get_output.outputs.TT_OUTPUT }}" ]; then
-            TT_VER=$(sed -n 's/.*TikTok: \(.*\)/\1/p' build.md | xargs)
-            TT_DLURL="$GITHUB_SERVER_URL/$GITHUB_REPOSITORY/releases/download/${{ steps.next_ver_code.outputs.NEXT_VER_CODE }}/${{ steps.get_output.outputs.TT_OUTPUT }}"
-            UPDATE_TT_JSON=$(get_update_json "$TT_VER" "${{ steps.next_ver_code.outputs.NEXT_VER_CODE}}" "$TT_DLURL" "$CHANGELOG_URL")
-            echo "$UPDATE_TT_JSON" >tt-update.json
-          fi
-
-          if [ -n "${{ steps.get_output.outputs.SP_OUTPUT }}" ]; then
-            SP_VER=$(sed -n 's/.*Spotify: \(.*\)/\1/p' build.md | xargs)
-            SP_DLURL="$GITHUB_SERVER_URL/$GITHUB_REPOSITORY/releases/download/${{ steps.next_ver_code.outputs.NEXT_VER_CODE }}/${{ steps.get_output.outputs.SP_OUTPUT }}"
-            UPDATE_SP_JSON=$(get_update_json "$SP_VER" "${{ steps.next_ver_code.outputs.NEXT_VER_CODE}}" "$SP_DLURL" "$CHANGELOG_URL")
-            echo "$UPDATE_SP_JSON" >sp-update.json
-          fi
-
-          if [ -n "${{ steps.get_output.outputs.WW_OUTPUT }}" ]; then
-            WW_VER=$(sed -n 's/.*WarnWetter: \(.*\)/\1/p' build.md | xargs)
-            WW_DLURL="$GITHUB_SERVER_URL/$GITHUB_REPOSITORY/releases/download/${{ steps.next_ver_code.outputs.NEXT_VER_CODE }}/${{ steps.get_output.outputs.WW_OUTPUT }}"
-            UPDATE_WW_JSON=$(get_update_json "$WW_VER" "${{ steps.next_ver_code.outputs.NEXT_VER_CODE}}" "$WW_DLURL" "$CHANGELOG_URL")
-            echo "$UPDATE_WW_JSON" >ww-update.json
-          fi
-          [ -z "$(find . -quit -type f -name "*.json")" ] && : >dummy.json
+          find . -name "*.json" | grep . || : >dummy.json
 
       - uses: stefanzweifel/git-auto-commit-action@v4.15.3
         with:
